#此文档在生产人员出厂时通过命令更改，在生产完成后谨慎更改-配置参数跟随单体
product_id: 20241029053       #产品编号
manufacture_date: 20241029    #生产日期
soft_version: 4.01.00         #软件版本号，软件升级时自动更新 预留
bdparamfix:                   #标度系数误差补偿
    fix_x: 360.000000
    fix_y: 360.000000
    fix_z: 360.000000
gyrodrift:                    #三轴陀螺零位
    drift_x: 0.000000
    drift_y: 0.000000
    drift_z: 0.000000
accbias:                      #三轴加表零位
    bias_x: 0.000000
    bias_y: 0.000000
    bias_z: 0.000000
encoder1_zero: 0.0            #电机编码器零位（内环）
encoder2_zero: 0.0            #电机编码器零位（外环）